report updated

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -46,9 +46,14 @@ jobs:
     - name: Ensure browsers are installed
       run: python -m playwright install --with-deps
 
-    - name: Test with pytest
+    - name: Run selenium pytests
       run: |
-        pytest tests/functional_tests/demo_test.py --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml
+        pytest tests/functional_tests/demo_test.py --doctest-modules --junitxml=junit/test-results-selenium-${{ matrix.python-version }}.xml
+
+    - name: Run playwright pytests
+      run: |
+        pytest tests/functional_tests/playwright_demo_test.py --doctest-modules --junitxml=junit/test-results-playwright-${{ matrix.python-version }}.xml
+
 #    - name: Upload pytest test results
 #      uses: actions/upload-artifact@v3
 #      with:
@@ -56,11 +61,18 @@ jobs:
 #        path: junit/test-results-${{ matrix.python-version }}.xml
 #      # Use always() to always run this step to publish test results when there are test failures
 #      if: ${{ always() }}
-    - name: Test Results
+    - name: Test Results Selenium
       uses: dorny/test-reporter@v1
       if: success() || failure()    # run this step even if previous step failed
       with:
-        name: UI tests            # Name of the check run which will be created
-        path: junit/test-results-${{ matrix.python-version }}.xml    # Path to test results
-#        path: /home/runner/work/XMCY-ODC-test/XMCY-ODC-test/junit/test-results-${{ matrix.python-version }}.xml
+        name: UI tests selenium            # Name of the check run which will be created
+        path: junit/test-results-selenium-${{ matrix.python-version }}.xml    # Path to test results
+        reporter: java-junit        # Format of test results
+
+    - name: Test Resultsuses Playwright
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: UI tests selenium            # Name of the check run which will be created
+        path: junit/test-results-playwright-${{ matrix.python-version }}.xml    # Path to test results
         reporter: java-junit        # Format of test results
